### ISSUE TITLE
About Training Model

### ISSUE THREAD

**Issue by sevkisahin** [naseemap47/CustomPose-Classification-Mediapipe#9]
Hi, thanks for greatfull work. But there is a point that i dont understand. What is the training architecture ? how many dense or conv. or ReLU or maxpooling ? Can you help me?

**Comment by naseemap47** [comment]
Hi @sevkisahin ,
you can look into this: https://github.com/naseemap47/CustomPose-Classification-Mediapipe/blob/master/poseModel.py#L40C1-L44C1
Think this will solve your issue. Thank you for using my repo.
If have any issue or doubt please let me know.
Thank You.
